name: ci
on:
  push: {}
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          # Will succeed on main, fail on the test branch
          test ! -f BREAK_ME
